travis:
  secure:
    BINSTAR_TOKEN: lAey0z27D1epav+74PPr3RvXqvavB85totNO5CazOC0AP7IlwBC5Vg1aJECdp0QR/jhBKgf8BxVX5h7KV4ytePt8ZQXbBFN3jYH7JhrzgfnEv28Q8534eIleyHbyuiLDYMODVHNdr6AYgUK5GHgwJR7ISmAZLuACu1EsladjQiOEJsnf8BLSpZguWYZJSkLiAJNa2k98OKahtlcjNW26BhWHC4S+KhXWp+W7OgCz3PIB4LGzoI/Wf4hS9xr9v48PtvVunyYil3/8MKTC/FdtcArcQ84RVqhMusE7oqCCAfdbsi1O+NwtbfT+podvnUw3kiS49oT99hKaV02SbB0bmcOgub3phdqoOFvBXhjhqSKecfcqGEZOzuVuogqLQi9r6IrdK4ceBfJvcj4/GYU8M6srFD3SKpu9aujLHRvlSJQ/N/5CBCqd3aG7TmZ7iaQwk5RUg39ORi69D5Zqs6SEGevQQ87u0p7wnwxwJzljxw0a/1gmlhlvAs1Q/P4g4vBvu5qZSHfiRNHNNbsIvLd0bVJxCln/TT8pe8MCVbTwYJCHPnhYGR0HTuk3G4f3VZSTit9FhAlXvOv3pBLlZ+yc0Y3f/ZeuifLE+v24IbPkpqjAuIuLr2EiGUrGB2bXdoZmuhdpDnyOWz5VjHgDAwQouxHmw7AH5zTtIeBSgSCBuK0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
