travis:
  secure:
    BINSTAR_TOKEN: KWI9Jhzmmr2skq7hxgzKs0HgzATwE4JxTSK92oLhUNYUPtUr8Q6W478OsotDwFUskRMuwJzEqbHf4+5h1utf4dBOrvlcvJ/hXznJotJFTD7+ABNSwrJy12JazdljsAbAXH03+b1FZ1I90o131gr08MaOGhJ3aF8gBFRIKmxHXrY/mkzhhWGh4pJbpeg1knT1qzszXLRloYQRZnaxfw4vTf/upIS6w+YgRlvQ7fb5hneMQD4IAlqJzDozvTwz6fSO/UqdjRhtPl6MP+8Lc/oxx+zQa+JQiFtoIjpqKA63NMnO83bss2kdvqf3Q1+cn24gsaSECfwHx51KQftAQ4bYK0MyDCzhiiWweQKgtG08XHyWHr6l7drZ6NfHk49JuJofEjGWSWNe9HCL/+WPLbOn+polmLseKPE0Mzd3KGUMp4j4GwChgeFG9Ers9x8EMmZAJtbW0ry2BLUE2s4KcJwbkVDa4DI+s91ZfBTMsPaGyKc2354ISnoIZIPJW6sEhMt603YucsN+ktJCujmjS5NumJsdVyHNin0q5s9lyQkrmAs8LOIIaqNvmeDVyWUJkOjE4k5mgbGI38HL7dF3I2+VNklA/BXEXnCLbEn5yDWcM2lCU4SpJqErjkFTiR/Hyv46CpScfHgfUH9X5ef0ZEWgyyZSxr7er5LdbQyj8wzi9Ek=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
