travis:
  secure:
    BINSTAR_TOKEN: ZCQr14oZfg244ve+3gfNWksT45hGQHOXBgsKBfEGJjWO6jm8x7mXl/yBS6z0Wp4JEGOq7Ppon+KsncSismwXITE/AmJyG+ttObO63bzrnj9DJs3TQnvmIR4cjYeFtE+ugG03mU2ZBewsGzv1hSkdLNMCQbVs6zolSZ5zdMeZo51rkWOwMavWhNlOv3/boS9MQG3dlsNCyaEcjZ3mho2eOlICvG6/QnQm0KD7vcDycvY0m73+iknwngtgfSwjnqcyAeG2nw0ma5oilN8FqFN/Rw5y6Z6XZev7fpJfKNzq5RYYtdKlyXB9h7PUo29lzltNKvHp+NCdnYfhuldA3He1EAGt2E9WoaDOSJn20yhQQ3hWuZimXdlh2GzN0uWGEbiJqygo1KUBg8rWkYLV1vHUbbeLeapleHLpne3g79i/lZLZ0+hrNUA6o9vvsDwTVonLfVC0japblb/gHGIdeUFSrWywYNgjElL2VxPmjXBA+Y0HhTncAhITEetuShsG1cC0vxW+LNElfilSXbJ5rtxH3apfVGoeZrx6iOoIBTWBbAWllgbP8y91b67DsAjQrwyviX9gb/VrKwdy6g93HiYFoRM8yZNKqZJwSF3teZi/2N70iAq0lW7v/P8fjM47dpABSo4sYTa2eeuf8AxVtxj5CSP5Crg2FvCnsqpHlUZxRQw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
